name: docker-build
# on: push
on:
  workflow_dispatch:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 21 * * *'
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
      TARGET: amd64
      REPOSITORY: nfvpe/multus
      REPOSITORY_USER: nfvperobot
    steps:    
      - uses: actions/checkout@v2
          
      - name: Clone upstream
        run: git clone --depth 1 https://github.com/ovn-org/ovn-kubernetes.git

      - name: Build image
        run: |
          cd ovn-kubernetes/dist/images
          make fedora

      - name: Tag image
        run: |
          docker tag ovn-kube-f:latest nfvpe/ovn-daemonset-u:latest
          docker tag ovn-kube-f:latest nfvpe/ovn-daemonset-u:$(date "+%F")
  
      - name: Login to registry
        run: docker login -u  ${{ secrets.REGISTRY_USER }} -p  ${{ secrets.REGISTRY_PASS }}
  
      - name: Push latest/snapshot images
        run: docker push nfvpe/ovn-daemonset-u:latest

