name: docker-build
on: push
# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron:  '40 20 * * *'
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      GO111MODULE: on
      TARGET: amd64
      REPOSITORY: nfvpe/multus
      REPOSITORY_USER: nfvperobot
    steps:    
      - uses: actions/checkout@v2
          
      - name: Clone upstream
        run: git clone --depth 1 https://github.com/ovn-org/ovn-kubernetes.git

      - name: Copy in our dockerfile
        run: cp -f Dockerfile.fedora.dev ./ovn-kubernetes/dist/images

      - name: Build image
        run: |
          cd ovn-kubernetes/dist/images
          sed -ie 's/`uname -r`/5.5.11-200.fc31.x86_64/' Makefile
          make fedora-dev

      - name: Tag image
        run: docker tag ovn-kube-f-dev:latest nfvpe/ovn-daemonset-u:latest
  
      - name: Login to registry
        run: docker login -u  ${{ secrets.REGISTRY_USER }} -p  ${{ secrets.REGISTRY_PASS }}
  
      - name: Push latest/snapshot images
        run: docker push nfvpe/ovn-daemonset-u:latest

